<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Updated Azure Static Web App</title>
    <style>
        /* Basic styling for the layout and appearance */
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f3f4f6;
        }
        .container {
            text-align: center;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }
        h1 {
            color: #333;
        }
        p {
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Updated heading to test auto-deployment -->
        <h1>Welcome to My Updated Static Web App!</h1>
        
        <!-- Updated paragraph to confirm changes reflect on the live site -->
        <p>This update should be automatically deployed to Azure!</p>
    </div>
</body>
</html>
